config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"

  get "pages/home", to: "pages#home"

  resources :recipes

  get "/signup", to: "chefs#new"
  resources :chefs, expect: [:new]

  get "/login", to:"sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to:"sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = self.email.to_s.downcase }
  validates :name, presence: true, length: { maximum:30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255},format: {with:VALID_EMAIL_REGEX},uniqueness: { case_sensitive: true}
  has_many :recipes, dependent: :destroy

  has_secure_password
  validates :password, presence: true, length: {minimum: 5}, allow_nil: true

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence:true
  validates :description, presence:true, length:{ minimum:5,maximum:300}
  belongs_to :chef
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_chef,:loggedin?

  def current_chef
    @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def loggedin?
    !!current_chef
  end

  def require_user
    if !loggedin?
      flash[:danger] = 'You need to be logged in to perform action'
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  before_action :set_chef, only: [:show,:edit,:update,:destroy]
  before_action :require_some_user, only: [:edit,:update,:destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 1)
  end

  def show
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page:1)
  end

  def new
    @chef = Chef.new
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:success] = "Updated Successfully"
      redirect_to @chef
    else
      render "edit"
    end
  end

  def destroy
    @chef.destroy
    flash[:danger] = " Deleted Successfully"
    redirect_to @chef
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:chef_id] = @chef_id
      flash[:success] = "Created Successfully"
      redirect_to chef_path(@chef)
    else
      render 'new'
    end
  end

  private
  def set_chef
    @chef = Chef.find(params[:id])
  end

  def chef_params
    params.require(:chef).permit(:name, :email, :password, :password_confirmation)
  end

  def require_some_user
    if current_chef != @chef && !current_chef.admin?
      flash[:danger] = "You need to login with your id"
      redirect_to chefs_path
    end
  end

  def require_admin
    if loggedin? && !current_chef.admin?
      flash[:danger] = "You need to login with your id"
      redirect_to chefs_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if loggedin?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show,:edit,:update,:destroy]
  before_action :require_user, expect: [:index,:show]
  before_action :require_some_user, only: [:edit,:update,:destroy]

  def index
    @recipe = Recipe.paginate(page: params[:page], per_page: 1)

  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(gotoParam)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = " Recipe Created Successfully "
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(gotoParam)
      flash[:success] = " Recipe Editted Successfully "
      redirect_to recipe_path(@recipe)
    else
      render "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:success] = " Recipe Deleted Successfully "
      redirect_to recipes_path
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def gotoParam
    params.require(:recipe).permit(:name, :description)
  end

  def require_some_user
    if current_chef != @recipe.chef && !current_chef.admin?
      flash[:danger] = "You can only perform action on recipes added by you"
      redirect_to recipes_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    chef = Chef.find_by(email: params[:sessions][:email].downcase)
    if chef && chef.authenticate(params[:sessions][:password])
      session[:chef_id] = chef.id
      flash[:success] = "Logged in successfully"
      redirect_to chef_path(chef)
    else
      flash.now[:danger] = "There was something wrong with credentials"
      render 'new'
    end

  end

  def destroy
    session[:chef_id] = nil
    flash.now[:success] = "You have logout"
    redirect_to root_path
  end

  private
  def format_param

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar(user,size: 80)
    # get the email from URL-parameters or what have you and make lowercase
    email_address = user.email.downcase

    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)

    # compile URL which can be used in <img src="RIGHT_HERE"...
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.name, class: 'img-circle')
  end
end

app/views/chefs/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, :html => {class: "form-horizontal", role:"form"}) do |f| %>
      <div class="form-group">
        <label for="exampleFormControlInput1">
          <%= f.label :name %>
        </label>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter Your Name" , autofocus: true %>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1"<%= f.label :email %></label>
        <%= f.email_field :email, class: "form-control", placeholder: "Enter Your Email"%>
      </div>
      <div class="form-group">
        <label for="exampleFormControlpassword"<%= f.label :password %></label>
        <%= f.password_field :password, class: "form-control", placeholder: "Choose Your password"%>
      </div>
      <div class="form-group">
        <label for="exampleFormControlpassword"<%= f.label :password_confirmation, "Confirm Password" %></label>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password"%>
      </div>


      <div class="form-group">
        <%= f.submit(@chef.new_record? ? "Create My Account" : "Update My Account",
                     class:"btn btn-primary") %>
      </div>

    <% end %>
    <div class="col-md-4 col-md-offset-4">
      [ <%= link_to "Cancel and Return to Recipe Lists", recipes_path %> ]
    </div>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render "shared/page_title", title: "Edit Your Profile" %>

<%= render "shared/errors_form", obj: @chef %>

<%= render "form"%>

app/views/chefs/index.html.erb
<%= render "shared/page_title", title: "Hello Chefs" %>

<div align="center">
  <%= will_paginate @chef %>
  <% @chefs.each do |chef| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-12 col-offset-12">
          <li>
            <%= link_to gravatar(chef), chef_path(chef)%>
          </li>
          <li class="chef-title">
            <%= link_to chef.name.capitalize, chef_path(chef)  %>
          </li>
          <li>
            <small><%= pluralize(chef.recipes.count,"recipe") if chef.recipes %></small>
          </li>
         <% if loggedin? && current_chef.admin? && !chef.admin? %>
          <li>
            <%= link_to "Delete this chef", chef_path(chef), method: :delete, data: {confirm:"Are you certain you want to delete all cehf and recipe"}  %>
          </li>
          <% end %>
         </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate @chef %>
</div>

app/views/chefs/new.html.erb
<%= render "shared/page_title", title: "Sign up for the registration" %>

<%= render "shared/errors_form", obj: @chef %>

<%= render "form"%>

app/views/chefs/show.html.erb
<%= render "shared/page_title", title: "Chef #{@chef.name} Profile" %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar(@chef,{size:120}) %>
  </div>
</div>

<h4 align="center"><%= @chef.name %>'s recipes</h4>
<div align="center">
  <%= will_paginate @chef_recipes %>
</div>
<%= render "recipes/recipes", obj: @chef_recipes %>
<div align="center">
  <%= will_paginate @chef_recipes %>
</div>

app/views/layouts/_footer.html.erb
<footer class="bs-docs-footer">
  <div class="container">

    <ul class="bs-docs-footer-links">
      <li><a href="https://github.com/twbs/bootstrap">GitHub</a></li>
      <li><a href="https://twitter.com/getbootstrap">Twitter</a></li>
      <li><a href="/docs/3.4/getting-started/#examples">Examples</a></li>
      <li><a href="/docs/3.4/about/">About</a></li>
    </ul>

    <p>Designed and built with all the love in the world by <a href="https://twitter.com/mdo" rel="noopener" target="_blank">@mdo</a> and <a href="https://twitter.com/fat" rel="noopener" target="_blank">@fat</a>. Maintained by the <a href="https://github.com/orgs/twbs/people">core team</a> with the help of <a href="https://github.com/twbs/bootstrap/graphs/contributors">our contributors</a>.</p>

    <p>Code licensed <a href="https://github.com/twbs/bootstrap/blob/v3-dev/LICENSE" rel="license noopener" target="_blank">MIT</a>, docs <a href="https://creativecommons.org/licenses/by/3.0/" rel="license noopener" target="_blank">CC BY 3.0</a>.</p>

  </div>
</footer>

app/views/layouts/_message.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name,msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Recipe" , root_path, class:"navbar-brand",id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "All Recipes" , recipes_path%>
        </li>
        <li>
          <%= link_to "Chef" , chefs_path%>
        </li>
        <% if loggedin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create New Recipe", new_recipe_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if loggedin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.name.capitalize %>'s Profile <%= "Admin" if current_chef.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Your Profile", chef_path(current_chef) %></li>
              <li><%= link_to "Edit Your Profile", edit_chef_path(current_chef) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "Login In", login_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/message' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to website</h1>
  <p>Perfect Place to find your answer</p>
  <p><%= link_to "Sign Up Or Log In", signup_path ,class:"btn btn-primary btn-lg"%></p>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render "shared/errors_form", obj: @recipe %>
<div class="row">
  <div class="col-md-12">
  <%= form_for(@recipe, :html => {class: "form-horizontal", role:"form"}) do |f| %>
    <div class="form-group">
      <label for="exampleFormControlInput1">
        <%= f.label :name %>
      </label>
      <%= f.text_field :name, class: "form-control", placeholder: "Recipe Name" , autofocus: true %>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1"<%= f.label :description %></label>
      <%= f.text_area :description, class: "form-control",rows: 10, placeholder: "How to make it?"%>
    </div>
    <div class="form-group">
      <%= f.submit class:"btn btn-primary" %>
    </div>
  <% end %>
    <div class="col-md-4 col-md-offset-4">
       [ <%= link_to "Cancel and Return to Recipe Lists", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipes.html.erb
<% obj.each do |r| %>
  <div class="row">
    <div class="col-md-2">
      <section class=" chef-info center">

        <%= gravatar(r.chef,{size:120})%>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to r.name, recipe_path(r) %></h4>
      <p>
        <%= truncate(r.description, length: 50) %>
      </p>
      <p>
        <span class="quite"><small>Created <%= time_ago_in_words(r.created_at)%> ago</small></span>
      </p>
      <% if loggedin? && (current_chef == r.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit The Recipe", edit_recipe_path(r), class:"btn btn-xs btn-warning"%>
          <%= link_to "Delete The Recipe", recipe_path(r), method: :delete, data:{ confirm:"Are you certain you want to delete this recipe"}, class:"btn btn-xs btn-danger"%>
        </div>
      <% end%>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render "shared/page_title", title: "Edit Your Recipe" %>
<hr />

<%= render "recipes/form" %>

app/views/recipes/index.html.erb
<%= render "shared/page_title", title: "Select Recipe"%>
<hr />

<div align="center">
  <%= will_paginate @recipe %>
</div>
<%= render "recipes/recipes", obj: @recipe %>
<div align="center">
  <%= will_paginate @recipe %>
</div>

app/views/recipes/new.html.erb
<%= render "shared/page_title", title: "Create Your New Recipe" %>
<hr />

<%= render "recipes/form" %>

app/views/recipes/show.html.erb
<%= render "shared/page_title", title: @recipe.name %>
<hr />

<div class="col-md-8 well col-md-offset-2">
  <h4 class="center description"><strong>Description</strong></h4>
  <hr />
  <%= simple_format(@recipe.description) %>

  <% if loggedin? && (current_chef == @recipe.chef || current_chef.admin?)%>
    <%= link_to "Edit The Recipe", edit_recipe_path(@recipe), class:"btn btn-xs btn-warning"%>
    <%= link_to "Delete The Recipe", recipe_path(@recipe), method: :delete, data:{ confirm:"Are you certain you want to delete this recipe"}, class:"btn btn-xs btn-danger"%>
  <% end %>

  <%= link_to "Return to the listing recipe", recipes_path , class:"btn btn-xs btn-primary"%>

  <div class="pull-right">
    <p class="center">
      Created by:
    </p>
    <p class="center">
      <%= gravatar(@recipe.chef)%>
    </p>
    <p class="center"><small><%= @recipe.chef.name %></small></p>
    <p>
      <span class="quite"><small>Created <%= time_ago_in_words(@recipe.created_at)%> ago</small></span>
    </p>
  </div>
  <p>

  </p>

</div>

app/views/shared/_errors_form.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved
          </h2>
          <div class="panel-body">
            <ul>
              <%= obj.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>